
spring:
  data:
    mongodb:
      # 库名称
      database: articledb
      # mongodb服务地址
      host: 127.0.0.1
      # 端口号
      port: 27017
      # 用户名
      username: mao
      # 密码
      password: "123456"
      # 可以使用uri连接
      #uri:  mongodb://mao:123456@127.0.0.1:27017/articledb
